import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark, neobrutalism, shadesOfPurple } from "@clerk/themes";

const mulish = Mulish({
  subsets: ["latin-ext"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-mulish",
});

export const metadata: Metadata = {
  title: "Finance-AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-PT">
      <body className={`${mulish.className} dark antialiased`}>
        <ClerkProvider
          appearance={{
            baseTheme: [dark, neobrutalism],
            variables: { colorPrimary: "blue" },
            signIn: {
              baseTheme: [shadesOfPurple],
              variables: { colorPrimary: "green" },
            },
          }}
        >
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
